name: Build Gitf

on:
  push:
    branch: ["main"]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          python -m pip install build
          pip install setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Upload distributions
        run: |
          gh release create "1.0.${{ github.run_number }}" dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.TK }}
        shell: bash
